services:
  tav-dashboard:
    container_name: tav-dashboard
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:3000'
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 350MB
        reservations:
          cpus: '0.25'
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true
